### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by ScotterC** [jrgifford/delayed_paperclip#179]
### For Version 3

* [x] Remove all adapters except AJ
* [x] Bump required Ruby version to 2.0
* [x] Bump required Rails version to 4.2
* [x] Refactoring
* [x] Cleanup Readme

## For Version 2.10

* [x] Deprecation Warnings https://github.com/jrgifford/delayed_paperclip/pull/178

Anything else?

**Comment by morgoth** [comment]
I think nothing more for 2.10

**Comment by ScotterC** [comment]
@morgoth cool. We'll leave the issue as is then 👍

**Comment by dwbutler** [comment]
I'm using the Delayed Job adapter because ActiveJob does not (yet) support setting job priority. We need image processing jobs to be enqueued with highest priority.

It would be great if the removed adapters could be extracted to separate gems instead of being removed entirely.

**Comment by morgoth** [comment]
@dwbutler I think it would require even more effort to maintain separate gems.

Do you think you could solve your issue in a little different way, like having 2 background processing serwers/pods/instances that process different queues, so one of them would process only important ones?

```
script/delayed_job --queue=critical start
script/delayed_job --queues=default,mailers,all-others start
```

**Comment by dwbutler** [comment]
Yes, the issue can be worked around in various ways.

The main problem, in my mind, is that ActiveJob will probably never support the full range of features in the different queueing systems. So only supporting ActiveJob is a step backwards.

I can only hope that in the future, ActiveJob will give better configuration control into the underlying implementation instead of forcing everyone to use a one-size-fits-all interface.

**Comment by jrgifford** [comment]
:+!:
